[package]
name = "singularity-rs"
version = "0.0.1"
authors = ["Felix Karg <fkarg10@gmail.com"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", rev = "3f491c88fbaee405c59312b601631f6e227c4422" }
# amethyst = { path = "../amethyst" }
log = { version = "0.4.6", features = ["serde"] }



[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
